language: php

php:
    - 5.6

env:
    - WP_VERSION=latest WP_MULTISITE=1

sudo: false

before_script:
    - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION 

script: phpunit
